apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-data
data:
  
  curl-script.sh: |
    #!/bin/sh
    
    function import_index {
        echo "Testing connection to Kibana"
        until $(curl -k -X GET http://${KIBANA_URL}:${KIBANA_PORT}/_cluster/health); do sleep 5; done
        until [ "$(curl -k -X GET http://${KIBANA_URL}:${KIBANA_PORT}/_cluster/health | wc -l)" == "0" ]
        do sleep 5
        done
        echo "Importing index..."
        OUTPUT=$(curl -k --user ${ELASTIC_USER}:${ELASTIC_PWD} -X POST http://${KIBANA_URL}:${KIBANA_PORT}/api/saved_objects/_import -H "kbn-xsrf: true" --form file=@/kibana/index_pattern.ndjson)
        SUCCESS=$(echo ${OUTPUT} | grep -o '"successCount":1' | wc -l)
        if [[ ${SUCCESS} == "1" ]]; then
          printf "\n########## Imported index-pattern successfully! #############################\n"
        else
          printf "\n########## Failure while importing index-pattern #############\n"
        fi
        echo ${OUTPUT}
    }

    import_index

  index_pattern.ndjson: |
    {"attributes":{"fieldAttrs":"{}","fields":"[]","runtimeFieldMap":"{}","timeFieldName":"@timestamp","title":"logstash-*","typeMeta":"{}"},"coreMigrationVersion":"8.2.2","id":"683a2d10-08fb-11ed-8cae-2d280a9cf5cc","migrationVersion":{"index-pattern":"8.0.0"},"references":[],"type":"index-pattern","updated_at":"2022-07-21T13:45:39.686Z","version":"WzEwNDUsMV0="}